language: java
sudo: required
dist: trusty

services:
  - mysql

jdk:
  - openjdk8
  - oraclejdk8

before_install:
  - mysql -uroot -e "CREATE DATABASE exm;"
  - mysql -uroot -e "CREATE USER emt@localhost IDENTIFIED BY 'eark';"
  - mysql -uroot -e "GRANT ALL PRIVILEGES ON exm.* TO 'emt'@'localhost';"
  - mysql -uroot < ./db/setup_db.sql

script:
  - mvn clean package
